site_name: Technical Documentation in Markdown
site_url: https://mydomain.org/mysite
remote_name: Technical document in Markdown
repo_url: https://github.com/Tuandl/technical-documentation-in-markdown-demo/tree/gh-pages
theme:
  name: material
  palette: 
    scheme: default
    primary: brown
    accent: deep orange
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
  - blog
  - tags
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format